/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author clara
 */
public class ConsultasEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form AltasEmpleado
     */
    public ConsultasEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jtfNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jtfAp = new javax.swing.JTextField();
        jtfAm = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jtfDni = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jcbDia = new javax.swing.JComboBox<>();
        jcbMes = new javax.swing.JComboBox<>();
        jcbAño = new javax.swing.JComboBox<>();
        jtfDireccion = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jcbSexo = new javax.swing.JComboBox<>();
        jtfSueldo = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jtfDniSuper = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jtfNoDpto = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        btnBuscar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(245, 198, 165));
        setPreferredSize(new java.awt.Dimension(960, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Buscar Empleado");
        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 41));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 880, 21));

        jtfNombre.setBorder(null);
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });
        add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 159, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 159, 20));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 159, 20));

        jtfAp.setBorder(null);
        add(jtfAp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 159, 30));

        jtfAm.setBorder(null);
        add(jtfAm, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 159, 30));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 159, 20));

        jtfDni.setBorder(null);
        add(jtfDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 159, 30));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 159, 20));

        jcbDia.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jcbDia.setForeground(new java.awt.Color(102, 102, 102));
        jcbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02" }));
        jcbDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDiaActionPerformed(evt);
            }
        });
        add(jcbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, 30));

        jcbMes.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jcbMes.setForeground(new java.awt.Color(102, 102, 102));
        jcbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ene", "Feb" }));
        jcbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMesActionPerformed(evt);
            }
        });
        add(jcbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, 30));

        jcbAño.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jcbAño.setForeground(new java.awt.Color(102, 102, 102));
        jcbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023" }));
        jcbAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAñoActionPerformed(evt);
            }
        });
        add(jcbAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, 30));

        jtfDireccion.setBorder(null);
        add(jtfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 190, 30));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 190, 20));

        jcbSexo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jcbSexo.setForeground(new java.awt.Color(102, 102, 102));
        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "H" }));
        jcbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSexoActionPerformed(evt);
            }
        });
        add(jcbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, 30));

        jtfSueldo.setBorder(null);
        add(jtfSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 130, 30));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 130, 20));

        jtfDniSuper.setBorder(null);
        add(jtfDniSuper, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 159, 30));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 159, 20));

        jtfNoDpto.setBorder(null);
        add(jtfNoDpto, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, 40, 30));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, 40, 20));

        btnBuscar.setBackground(new java.awt.Color(162, 65, 107));
        btnBuscar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 120, 30));

        btnBorrar.setBackground(new java.awt.Color(162, 65, 107));
        btnBorrar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(null);
        add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 120, 30));

        btnCancelar.setBackground(new java.awt.Color(162, 65, 107));
        btnCancelar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 120, 30));

        jRadioButton1.setBackground(new java.awt.Color(245, 198, 165));
        jRadioButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton1.setText("Apellido materno");
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, 30));

        jRadioButton2.setBackground(new java.awt.Color(245, 198, 165));
        jRadioButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton2.setText("Dni");
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jRadioButton3.setBackground(new java.awt.Color(245, 198, 165));
        jRadioButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton3.setText("Fecha de nacimiento");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, 30));

        jRadioButton4.setBackground(new java.awt.Color(245, 198, 165));
        jRadioButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton4.setText("Apellido paterno");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, 30));

        jRadioButton5.setBackground(new java.awt.Color(245, 198, 165));
        jRadioButton5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton5.setText("Número departamento");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, -1, -1));

        jRadioButton6.setBackground(new java.awt.Color(245, 198, 165));
        jRadioButton6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton6.setText("Dirección");
        add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, 30));

        jRadioButton7.setBackground(new java.awt.Color(245, 198, 165));
        jRadioButton7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton7.setText("Nombre(s)");
        add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 30));

        jRadioButton8.setBackground(new java.awt.Color(245, 198, 165));
        jRadioButton8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton8.setText("Todos");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jRadioButton9.setBackground(new java.awt.Color(245, 198, 165));
        jRadioButton9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton9.setText("Sexo");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jRadioButton10.setBackground(new java.awt.Color(245, 198, 165));
        jRadioButton10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton10.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton10.setText("Sueldo");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jRadioButton11.setBackground(new java.awt.Color(245, 198, 165));
        jRadioButton11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton11.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton11.setText("Dni supervisor");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jcbAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAñoActionPerformed

    private void jcbDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDiaActionPerformed

    private void jcbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSexoActionPerformed

    private void jcbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMesActionPerformed

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JComboBox<String> jcbAño;
    private javax.swing.JComboBox<String> jcbDia;
    private javax.swing.JComboBox<String> jcbMes;
    private javax.swing.JComboBox<String> jcbSexo;
    private javax.swing.JTextField jtfAm;
    private javax.swing.JTextField jtfAp;
    private javax.swing.JTextField jtfDireccion;
    private javax.swing.JTextField jtfDni;
    private javax.swing.JTextField jtfDniSuper;
    private javax.swing.JTextField jtfNoDpto;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfSueldo;
    // End of variables declaration//GEN-END:variables
}
