/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import contolador.EmpleadoDAO;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ScrollPaneConstants;
import modelo.Empleado;
import modelo.Reporte;

/**
 *
 * @author clara
 */
public class MenuEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form MenuEmpleado1
     */
    String sqlE = "SELECT * FROM empleado";
    private Component rootPane;
    
    public MenuEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtpContenidoABCC = new javax.swing.JTabbedPane();
        jpAltas = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Nombre = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        ApellidoP = new javax.swing.JLabel();
        jtfAp = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        ApellidoM = new javax.swing.JLabel();
        jtfAm = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Dni = new javax.swing.JLabel();
        jtfDni = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        FechaNac = new javax.swing.JLabel();
        jcbAño = new javax.swing.JComboBox<>();
        jcbMes = new javax.swing.JComboBox<>();
        jcbDia = new javax.swing.JComboBox<>();
        Direccion = new javax.swing.JLabel();
        jtfDireccion = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        Sexo = new javax.swing.JLabel();
        jcbSexo = new javax.swing.JComboBox<>();
        Sueldo = new javax.swing.JLabel();
        jtfSueldo = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        DniSuper = new javax.swing.JLabel();
        jtfDniSuper = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        NoDpto = new javax.swing.JLabel();
        jtfNoDpto = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        btnAgregar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jpBajas = new javax.swing.JPanel();
        Titulo1 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        Dni1 = new javax.swing.JLabel();
        jtfDni1 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        btnEliminar = new javax.swing.JButton();
        btnBorrar1 = new javax.swing.JButton();
        jpCambios = new javax.swing.JPanel();
        Titulo2 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        Nombre1 = new javax.swing.JLabel();
        jtfNombre1 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        ApellidoP1 = new javax.swing.JLabel();
        jtfAp1 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        ApellidoM1 = new javax.swing.JLabel();
        jtfAm1 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        Dni2 = new javax.swing.JLabel();
        jtfDni2 = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        FechaNac1 = new javax.swing.JLabel();
        jcbDia1 = new javax.swing.JComboBox<>();
        jcbMes1 = new javax.swing.JComboBox<>();
        jcbAño1 = new javax.swing.JComboBox<>();
        Direccion1 = new javax.swing.JLabel();
        jtfDireccion1 = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        Sexo1 = new javax.swing.JLabel();
        jcbSexo1 = new javax.swing.JComboBox<>();
        Sueldo1 = new javax.swing.JLabel();
        jtfSueldo1 = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        DniSuper1 = new javax.swing.JLabel();
        jtfDniSuper1 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        NoDpto1 = new javax.swing.JLabel();
        jtfNoDpto1 = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        btnGuardar2 = new javax.swing.JButton();
        btnBorrar2 = new javax.swing.JButton();
        jpConsultas = new javax.swing.JPanel();
        Titulo3 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        Nombre2 = new javax.swing.JLabel();
        jtfNombre2 = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        ApellidoP2 = new javax.swing.JLabel();
        jtfAp2 = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        ApellidoM2 = new javax.swing.JLabel();
        jtfAm2 = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        Dni3 = new javax.swing.JLabel();
        jtfDni3 = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        FechaNac2 = new javax.swing.JLabel();
        jcbDia2 = new javax.swing.JComboBox<>();
        jcbMes2 = new javax.swing.JComboBox<>();
        jcbAño2 = new javax.swing.JComboBox<>();
        Direccion2 = new javax.swing.JLabel();
        jtfDireccion2 = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        Sexo2 = new javax.swing.JLabel();
        jcbSexo2 = new javax.swing.JComboBox<>();
        Sueldo2 = new javax.swing.JLabel();
        jtfSueldo2 = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        DniSuper2 = new javax.swing.JLabel();
        jtfDniSuper2 = new javax.swing.JTextField();
        jSeparator28 = new javax.swing.JSeparator();
        NoDpto2 = new javax.swing.JLabel();
        jtfNoDpto2 = new javax.swing.JTextField();
        jSeparator29 = new javax.swing.JSeparator();
        btnBorrar3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnGenerarR = new javax.swing.JButton();
        Titulo4 = new javax.swing.JLabel();
        jSeparator30 = new javax.swing.JSeparator();
        jpTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TabDniS = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 198, 165));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setBackground(new java.awt.Color(162, 65, 107));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Empleado");

        javax.swing.GroupLayout jpTituloLayout = new javax.swing.GroupLayout(jpTitulo);
        jpTitulo.setLayout(jpTituloLayout);
        jpTituloLayout.setHorizontalGroup(
            jpTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(819, Short.MAX_VALUE))
        );
        jpTituloLayout.setVerticalGroup(
            jpTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTituloLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );

        add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 100));

        jtpContenidoABCC.setBackground(new java.awt.Color(245, 198, 165));
        jtpContenidoABCC.setForeground(new java.awt.Color(102, 102, 102));
        jtpContenidoABCC.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jtpContenidoABCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtpContenidoABCCMouseClicked(evt);
            }
        });
        jtpContenidoABCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtpContenidoABCCKeyPressed(evt);
            }
        });

        jpAltas.setBackground(new java.awt.Color(245, 198, 165));
        jpAltas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jpAltas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Agregar Empleado");
        jpAltas.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 41));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 880, 21));

        Nombre.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(102, 102, 102));
        Nombre.setText("Nombre");
        jpAltas.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        jtfNombre.setBackground(new java.awt.Color(245, 198, 165));
        jtfNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfNombre.setBorder(null);
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });
        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombreKeyTyped(evt);
            }
        });
        jpAltas.add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 110, 180, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 140, 180, 20));

        ApellidoP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ApellidoP.setForeground(new java.awt.Color(102, 102, 102));
        ApellidoP.setText("Apellido paterno");
        jpAltas.add(ApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, 30));

        jtfAp.setBackground(new java.awt.Color(245, 198, 165));
        jtfAp.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfAp.setBorder(null);
        jtfAp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfApKeyPressed(evt);
            }
        });
        jpAltas.add(jtfAp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 159, 30));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 159, 20));

        ApellidoM.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ApellidoM.setForeground(new java.awt.Color(102, 102, 102));
        ApellidoM.setText("Apellido materno");
        jpAltas.add(ApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, 30));

        jtfAm.setBackground(new java.awt.Color(245, 198, 165));
        jtfAm.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfAm.setBorder(null);
        jtfAm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfAmKeyPressed(evt);
            }
        });
        jpAltas.add(jtfAm, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 159, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 159, 20));

        Dni.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Dni.setForeground(new java.awt.Color(102, 102, 102));
        Dni.setText("Dni");
        jpAltas.add(Dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 30));

        jtfDni.setBackground(new java.awt.Color(245, 198, 165));
        jtfDni.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfDni.setBorder(null);
        jtfDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDniKeyPressed(evt);
            }
        });
        jpAltas.add(jtfDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 159, 30));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 159, 20));

        FechaNac.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FechaNac.setForeground(new java.awt.Color(102, 102, 102));
        FechaNac.setText("Fecha de nacimiento");
        jpAltas.add(FechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, 30));

        jcbAño.setBackground(new java.awt.Color(162, 65, 107));
        jcbAño.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jcbAño.setForeground(new java.awt.Color(102, 102, 102));
        jcbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005" }));
        jcbAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAñoActionPerformed(evt);
            }
        });
        jpAltas.add(jcbAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, 30));

        jcbMes.setBackground(new java.awt.Color(162, 65, 107));
        jcbMes.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jcbMes.setForeground(new java.awt.Color(102, 102, 102));
        jcbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        jcbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMesActionPerformed(evt);
            }
        });
        jpAltas.add(jcbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, 30));

        jcbDia.setBackground(new java.awt.Color(162, 65, 107));
        jcbDia.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jcbDia.setForeground(new java.awt.Color(102, 102, 102));
        jcbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jcbDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDiaActionPerformed(evt);
            }
        });
        jpAltas.add(jcbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, 30));

        Direccion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Direccion.setForeground(new java.awt.Color(102, 102, 102));
        Direccion.setText("Dirección");
        jpAltas.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, 30));

        jtfDireccion.setBackground(new java.awt.Color(245, 198, 165));
        jtfDireccion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfDireccion.setBorder(null);
        jtfDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDireccionKeyPressed(evt);
            }
        });
        jpAltas.add(jtfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 190, 30));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 190, 20));

        Sexo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Sexo.setForeground(new java.awt.Color(102, 102, 102));
        Sexo.setText("Sexo");
        jpAltas.add(Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));

        jcbSexo.setBackground(new java.awt.Color(162, 65, 107));
        jcbSexo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jcbSexo.setForeground(new java.awt.Color(102, 102, 102));
        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "H" }));
        jcbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSexoActionPerformed(evt);
            }
        });
        jpAltas.add(jcbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 30));

        Sueldo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Sueldo.setForeground(new java.awt.Color(102, 102, 102));
        Sueldo.setText("Sueldo");
        jpAltas.add(Sueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, 30));

        jtfSueldo.setBackground(new java.awt.Color(245, 198, 165));
        jtfSueldo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfSueldo.setBorder(null);
        jtfSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSueldoKeyPressed(evt);
            }
        });
        jpAltas.add(jtfSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 130, 30));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 130, 20));

        DniSuper.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DniSuper.setForeground(new java.awt.Color(102, 102, 102));
        DniSuper.setText("Dni supervisor");
        jpAltas.add(DniSuper, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, 30));

        jtfDniSuper.setBackground(new java.awt.Color(245, 198, 165));
        jtfDniSuper.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfDniSuper.setBorder(null);
        jtfDniSuper.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDniSuperKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDniSuperKeyReleased(evt);
            }
        });
        jpAltas.add(jtfDniSuper, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 159, 30));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 159, 20));

        NoDpto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NoDpto.setForeground(new java.awt.Color(102, 102, 102));
        NoDpto.setText("Número departamento");
        jpAltas.add(NoDpto, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, 30));

        jtfNoDpto.setBackground(new java.awt.Color(245, 198, 165));
        jtfNoDpto.setBorder(null);
        jtfNoDpto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNoDptoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNoDptoKeyReleased(evt);
            }
        });
        jpAltas.add(jtfNoDpto, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, 40, 30));
        jpAltas.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, 40, 20));

        btnAgregar.setBackground(new java.awt.Color(162, 65, 107));
        btnAgregar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jpAltas.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 120, 30));

        btnBorrar.setBackground(new java.awt.Color(162, 65, 107));
        btnBorrar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(null);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jpAltas.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 120, 30));

        jtpContenidoABCC.addTab("Altas", jpAltas);

        jpBajas.setBackground(new java.awt.Color(245, 198, 165));
        jpBajas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo1.setBackground(new java.awt.Color(255, 255, 255));
        Titulo1.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setText("Eliminar Empleado");
        jpBajas.add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 41));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jpBajas.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 880, 21));

        Dni1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Dni1.setForeground(new java.awt.Color(102, 102, 102));
        Dni1.setText("Dni");
        jpBajas.add(Dni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 30));

        jtfDni1.setBackground(new java.awt.Color(245, 198, 165));
        jtfDni1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfDni1.setBorder(null);
        jtfDni1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDni1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDni1KeyReleased(evt);
            }
        });
        jpBajas.add(jtfDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 159, 30));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        jpBajas.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 159, 20));

        btnEliminar.setBackground(new java.awt.Color(162, 65, 107));
        btnEliminar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jpBajas.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 120, 30));

        btnBorrar1.setBackground(new java.awt.Color(162, 65, 107));
        btnBorrar1.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBorrar1.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar1.setText("Borrar");
        btnBorrar1.setBorder(null);
        btnBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar1ActionPerformed(evt);
            }
        });
        jpBajas.add(btnBorrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 120, 30));

        jtpContenidoABCC.addTab("Bajas", jpBajas);

        jpCambios.setBackground(new java.awt.Color(245, 198, 165));
        jpCambios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo2.setBackground(new java.awt.Color(255, 255, 255));
        Titulo2.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo2.setForeground(new java.awt.Color(255, 255, 255));
        Titulo2.setText("Modificar Empleado");
        jpCambios.add(Titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 41));

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 880, 21));

        Nombre1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Nombre1.setForeground(new java.awt.Color(102, 102, 102));
        Nombre1.setText("Nombre");
        jpCambios.add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        jtfNombre1.setBackground(new java.awt.Color(245, 198, 165));
        jtfNombre1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfNombre1.setBorder(null);
        jtfNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombre1ActionPerformed(evt);
            }
        });
        jtfNombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNombre1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNombre1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombre1KeyTyped(evt);
            }
        });
        jpCambios.add(jtfNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 110, 180, 30));

        jSeparator13.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 140, 180, 20));

        ApellidoP1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ApellidoP1.setForeground(new java.awt.Color(102, 102, 102));
        ApellidoP1.setText("Apellido paterno");
        jpCambios.add(ApellidoP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, 30));

        jtfAp1.setBackground(new java.awt.Color(245, 198, 165));
        jtfAp1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfAp1.setBorder(null);
        jtfAp1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfAp1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfAp1KeyReleased(evt);
            }
        });
        jpCambios.add(jtfAp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 159, 30));

        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 159, 20));

        ApellidoM1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ApellidoM1.setForeground(new java.awt.Color(102, 102, 102));
        ApellidoM1.setText("Apellido materno");
        jpCambios.add(ApellidoM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, 30));

        jtfAm1.setBackground(new java.awt.Color(245, 198, 165));
        jtfAm1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfAm1.setBorder(null);
        jtfAm1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfAm1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfAm1KeyReleased(evt);
            }
        });
        jpCambios.add(jtfAm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 159, 30));

        jSeparator15.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 159, 20));

        Dni2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Dni2.setForeground(new java.awt.Color(102, 102, 102));
        Dni2.setText("Dni");
        jpCambios.add(Dni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 30));

        jtfDni2.setBackground(new java.awt.Color(245, 198, 165));
        jtfDni2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfDni2.setBorder(null);
        jtfDni2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDni2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDni2KeyReleased(evt);
            }
        });
        jpCambios.add(jtfDni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 159, 30));

        jSeparator18.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 159, 20));

        FechaNac1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FechaNac1.setForeground(new java.awt.Color(102, 102, 102));
        FechaNac1.setText("Fecha de nacimiento");
        jpCambios.add(FechaNac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, 30));

        jcbDia1.setBackground(new java.awt.Color(162, 65, 107));
        jcbDia1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jcbDia1.setForeground(new java.awt.Color(102, 102, 102));
        jcbDia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jcbDia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDia1ActionPerformed(evt);
            }
        });
        jpCambios.add(jcbDia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, 30));

        jcbMes1.setBackground(new java.awt.Color(162, 65, 107));
        jcbMes1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jcbMes1.setForeground(new java.awt.Color(102, 102, 102));
        jcbMes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        jcbMes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMes1ActionPerformed(evt);
            }
        });
        jpCambios.add(jcbMes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, 30));

        jcbAño1.setBackground(new java.awt.Color(162, 65, 107));
        jcbAño1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jcbAño1.setForeground(new java.awt.Color(102, 102, 102));
        jcbAño1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005" }));
        jcbAño1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAño1ActionPerformed(evt);
            }
        });
        jpCambios.add(jcbAño1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, 30));

        Direccion1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Direccion1.setForeground(new java.awt.Color(102, 102, 102));
        Direccion1.setText("Dirección");
        jpCambios.add(Direccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, 30));

        jtfDireccion1.setBackground(new java.awt.Color(245, 198, 165));
        jtfDireccion1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfDireccion1.setBorder(null);
        jtfDireccion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDireccion1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDireccion1KeyReleased(evt);
            }
        });
        jpCambios.add(jtfDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 190, 30));

        jSeparator20.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 190, 20));

        Sexo1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Sexo1.setForeground(new java.awt.Color(102, 102, 102));
        Sexo1.setText("Sexo");
        jpCambios.add(Sexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));

        jcbSexo1.setBackground(new java.awt.Color(162, 65, 107));
        jcbSexo1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jcbSexo1.setForeground(new java.awt.Color(102, 102, 102));
        jcbSexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "H" }));
        jcbSexo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSexo1ActionPerformed(evt);
            }
        });
        jpCambios.add(jcbSexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 30));

        Sueldo1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Sueldo1.setForeground(new java.awt.Color(102, 102, 102));
        Sueldo1.setText("Sueldo");
        jpCambios.add(Sueldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, 30));

        jtfSueldo1.setBackground(new java.awt.Color(245, 198, 165));
        jtfSueldo1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfSueldo1.setBorder(null);
        jtfSueldo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSueldo1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfSueldo1KeyReleased(evt);
            }
        });
        jpCambios.add(jtfSueldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 130, 30));

        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 130, 20));

        DniSuper1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DniSuper1.setForeground(new java.awt.Color(102, 102, 102));
        DniSuper1.setText("Dni supervisor");
        jpCambios.add(DniSuper1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, 30));

        jtfDniSuper1.setBackground(new java.awt.Color(245, 198, 165));
        jtfDniSuper1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfDniSuper1.setBorder(null);
        jtfDniSuper1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDniSuper1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDniSuper1KeyReleased(evt);
            }
        });
        jpCambios.add(jtfDniSuper1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 159, 30));

        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 159, 20));

        NoDpto1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NoDpto1.setForeground(new java.awt.Color(102, 102, 102));
        NoDpto1.setText("Número departamento");
        jpCambios.add(NoDpto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, 30));

        jtfNoDpto1.setBackground(new java.awt.Color(245, 198, 165));
        jtfNoDpto1.setBorder(null);
        jtfNoDpto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNoDpto1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNoDpto1KeyReleased(evt);
            }
        });
        jpCambios.add(jtfNoDpto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, 40, 30));
        jpCambios.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, 40, 20));

        btnGuardar2.setBackground(new java.awt.Color(162, 65, 107));
        btnGuardar2.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnGuardar2.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar2.setText("Guardar cambios");
        btnGuardar2.setBorder(null);
        btnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar2ActionPerformed(evt);
            }
        });
        jpCambios.add(btnGuardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 160, 30));

        btnBorrar2.setBackground(new java.awt.Color(162, 65, 107));
        btnBorrar2.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBorrar2.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar2.setText("Borrar");
        btnBorrar2.setBorder(null);
        btnBorrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar2ActionPerformed(evt);
            }
        });
        jpCambios.add(btnBorrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 120, 30));

        jtpContenidoABCC.addTab("Cambios", jpCambios);

        jpConsultas.setBackground(new java.awt.Color(245, 198, 165));
        jpConsultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo3.setBackground(new java.awt.Color(255, 255, 255));
        Titulo3.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo3.setForeground(new java.awt.Color(255, 255, 255));
        Titulo3.setText("Buscar");
        jpConsultas.add(Titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 41));

        jSeparator21.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 880, 21));

        Nombre2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Nombre2.setForeground(new java.awt.Color(102, 102, 102));
        Nombre2.setText("Nombre");
        jpConsultas.add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        jtfNombre2.setBackground(new java.awt.Color(245, 198, 165));
        jtfNombre2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfNombre2.setBorder(null);
        jtfNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombre2ActionPerformed(evt);
            }
        });
        jtfNombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNombre2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNombre2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombre2KeyTyped(evt);
            }
        });
        jpConsultas.add(jtfNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 110, 170, 30));

        jSeparator22.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 140, 180, 20));

        ApellidoP2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ApellidoP2.setForeground(new java.awt.Color(102, 102, 102));
        ApellidoP2.setText("Apellido paterno");
        jpConsultas.add(ApellidoP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, 30));

        jtfAp2.setBackground(new java.awt.Color(245, 198, 165));
        jtfAp2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfAp2.setBorder(null);
        jtfAp2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfAp2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfAp2KeyReleased(evt);
            }
        });
        jpConsultas.add(jtfAp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 159, 30));

        jSeparator23.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 159, 20));

        ApellidoM2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ApellidoM2.setForeground(new java.awt.Color(102, 102, 102));
        ApellidoM2.setText("Apellido materno");
        jpConsultas.add(ApellidoM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, 30));

        jtfAm2.setBackground(new java.awt.Color(245, 198, 165));
        jtfAm2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfAm2.setBorder(null);
        jtfAm2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfAm2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfAm2KeyReleased(evt);
            }
        });
        jpConsultas.add(jtfAm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 159, 30));

        jSeparator24.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 159, 20));

        Dni3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Dni3.setForeground(new java.awt.Color(102, 102, 102));
        Dni3.setText("Dni");
        jpConsultas.add(Dni3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 30));

        jtfDni3.setBackground(new java.awt.Color(245, 198, 165));
        jtfDni3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfDni3.setBorder(null);
        jtfDni3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDni3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDni3KeyReleased(evt);
            }
        });
        jpConsultas.add(jtfDni3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 159, 30));

        jSeparator25.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 159, 20));

        FechaNac2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FechaNac2.setForeground(new java.awt.Color(102, 102, 102));
        FechaNac2.setText("Fecha de nacimiento");
        jpConsultas.add(FechaNac2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, 30));

        jcbDia2.setBackground(new java.awt.Color(162, 65, 107));
        jcbDia2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jcbDia2.setForeground(new java.awt.Color(102, 102, 102));
        jcbDia2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jcbDia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDia2ActionPerformed(evt);
            }
        });
        jpConsultas.add(jcbDia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, 30));

        jcbMes2.setBackground(new java.awt.Color(162, 65, 107));
        jcbMes2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jcbMes2.setForeground(new java.awt.Color(102, 102, 102));
        jcbMes2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        jcbMes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMes2ActionPerformed(evt);
            }
        });
        jpConsultas.add(jcbMes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, 30));

        jcbAño2.setBackground(new java.awt.Color(162, 65, 107));
        jcbAño2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jcbAño2.setForeground(new java.awt.Color(102, 102, 102));
        jcbAño2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005" }));
        jcbAño2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAño2ActionPerformed(evt);
            }
        });
        jpConsultas.add(jcbAño2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, 30));

        Direccion2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Direccion2.setForeground(new java.awt.Color(102, 102, 102));
        Direccion2.setText("Dirección");
        jpConsultas.add(Direccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, 30));

        jtfDireccion2.setBackground(new java.awt.Color(245, 198, 165));
        jtfDireccion2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfDireccion2.setBorder(null);
        jtfDireccion2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDireccion2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDireccion2KeyReleased(evt);
            }
        });
        jpConsultas.add(jtfDireccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 190, 30));

        jSeparator26.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 190, 20));

        Sexo2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Sexo2.setForeground(new java.awt.Color(102, 102, 102));
        Sexo2.setText("Sexo");
        jpConsultas.add(Sexo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));

        jcbSexo2.setBackground(new java.awt.Color(162, 65, 107));
        jcbSexo2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jcbSexo2.setForeground(new java.awt.Color(102, 102, 102));
        jcbSexo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "H" }));
        jcbSexo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSexo2ActionPerformed(evt);
            }
        });
        jpConsultas.add(jcbSexo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 30));

        Sueldo2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Sueldo2.setForeground(new java.awt.Color(102, 102, 102));
        Sueldo2.setText("Sueldo");
        jpConsultas.add(Sueldo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, 30));

        jtfSueldo2.setBackground(new java.awt.Color(245, 198, 165));
        jtfSueldo2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfSueldo2.setBorder(null);
        jtfSueldo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSueldo2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfSueldo2KeyReleased(evt);
            }
        });
        jpConsultas.add(jtfSueldo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 130, 30));

        jSeparator27.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 130, 20));

        DniSuper2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DniSuper2.setForeground(new java.awt.Color(102, 102, 102));
        DniSuper2.setText("Dni supervisor");
        jpConsultas.add(DniSuper2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, 30));

        jtfDniSuper2.setBackground(new java.awt.Color(245, 198, 165));
        jtfDniSuper2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfDniSuper2.setBorder(null);
        jtfDniSuper2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDniSuper2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDniSuper2KeyReleased(evt);
            }
        });
        jpConsultas.add(jtfDniSuper2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 159, 30));

        jSeparator28.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 159, 20));

        NoDpto2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NoDpto2.setForeground(new java.awt.Color(102, 102, 102));
        NoDpto2.setText("Número departamento");
        jpConsultas.add(NoDpto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, 30));

        jtfNoDpto2.setBackground(new java.awt.Color(245, 198, 165));
        jtfNoDpto2.setBorder(null);
        jtfNoDpto2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNoDpto2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNoDpto2KeyReleased(evt);
            }
        });
        jpConsultas.add(jtfNoDpto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, 40, 30));
        jpConsultas.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, 40, 20));

        btnBorrar3.setBackground(new java.awt.Color(162, 65, 107));
        btnBorrar3.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBorrar3.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar3.setText("Borrar");
        btnBorrar3.setBorder(null);
        btnBorrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar3ActionPerformed(evt);
            }
        });
        jpConsultas.add(btnBorrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 120, 30));

        jtpContenidoABCC.addTab("Consultas", jpConsultas);

        jPanel1.setBackground(new java.awt.Color(245, 198, 165));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGenerarR.setBackground(new java.awt.Color(162, 65, 107));
        btnGenerarR.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnGenerarR.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarR.setText("Generar reporte");
        btnGenerarR.setBorder(null);
        btnGenerarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarRActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 140, 50));

        Titulo4.setBackground(new java.awt.Color(255, 255, 255));
        Titulo4.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo4.setForeground(new java.awt.Color(255, 255, 255));
        Titulo4.setText("Generar reporte de empleados");
        jPanel1.add(Titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 41));

        jSeparator30.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 880, 21));

        jtpContenidoABCC.addTab("Reporte", jPanel1);

        add(jtpContenidoABCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 960, 390));

        jpTabla.setBackground(new java.awt.Color(255, 255, 255));
        jpTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jpTabla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 190));

        TabDniS.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        TabDniS.setText("Tablas Dni supervisor y Num dpto");
        jpTabla.add(TabDniS, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 160, 20));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jpTabla.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 100, 170));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jpTabla.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 50, 170));

        add(jpTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 960, 210));
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jcbAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAñoActionPerformed

    private void jcbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSexoActionPerformed

    private void jtfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreKeyTyped

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        EmpleadoDAO eDAO = new EmpleadoDAO();
        if(jtfNombre.getText().equals("")||jtfAp.getText().equals("")||jtfAm.getText().equals("")||jtfDni.getText().equals("")||
                (jcbDia.getSelectedItem().equals("01")&&jcbMes.getSelectedItem().equals("01")&&jcbAño.getSelectedItem().equals("1940"))||
                jtfDireccion.getText().equals("")||jtfSueldo.getText().equals("")||jtfDniSuper.getText().equals("")||
                jtfNoDpto.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debes completar todos los campos");
        }else{
            String nombre = jtfNombre.getText();
            String ap = jtfAp.getText();
            String am = jtfAm.getText();
            String dni = jtfDni.getText();
            String fecha = obtenerFecha(jcbDia, jcbMes, jcbAño);
            String direccion = jtfDireccion.getText();
            String sexo = (String) jcbSexo.getSelectedItem();
            int sueldo = Integer.parseInt(jtfSueldo.getText());
            String dniSuper = jtfDniSuper.getText();
            byte noDpto = Byte.parseByte(jtfNoDpto.getText());
            Empleado e = new Empleado(nombre,ap,am,dni,fecha,direccion,sexo,sueldo,dniSuper,noDpto);
            
            if(eDAO.insertarRragistro(e)){
                JOptionPane.showMessageDialog(rootPane,"Se agregó correctamente a la base de datos");
            }else{
                JOptionPane.showMessageDialog(rootPane,"Hubo un error al intentar agregar a la base de datos");
            }
            mostrarTabla(sqlE);
        }
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        restablecerComponentes(jtfNombre, jtfAp,jtfAm, jtfDni, jcbDia, jcbMes, jcbAño, jtfDireccion, jcbSexo, jtfSueldo, jtfDniSuper, jtfNoDpto);
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar1ActionPerformed
        restablecerComponentes(jtfDni1);
    }//GEN-LAST:event_btnBorrar1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        EmpleadoDAO eDAO = new EmpleadoDAO();
        if(jtfDni1.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Debes ingresar el dni de un empleado");
        }else{
            String dni = jtfDni1.getText();
            if(eDAO.eliminarRegistro(dni)){
                JOptionPane.showMessageDialog(rootPane,"Se eliminó correctamente de la base de datos");
            }else{
                JOptionPane.showMessageDialog(rootPane,"Hubo un error al intentar eliminar a la base de datos");
            }
        }
        mostrarTabla(sqlE);     
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jtfNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombre1ActionPerformed

    private void jtfNombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombre1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombre1KeyTyped

    private void jcbSexo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSexo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSexo1ActionPerformed

    private void jcbDia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDia1ActionPerformed

    private void jcbMes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMes1ActionPerformed

    private void jcbAño1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAño1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAño1ActionPerformed

    private void btnBorrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar2ActionPerformed
        restablecerComponentes(jtfNombre1, jtfAp1,jtfAm1, jtfDni2, jcbDia1, jcbMes1, jcbAño1, jtfDireccion1, jcbSexo1, jtfSueldo1, jtfDniSuper1, jtfNoDpto1);
    }//GEN-LAST:event_btnBorrar2ActionPerformed

    private void btnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar2ActionPerformed
        EmpleadoDAO eDAO = new EmpleadoDAO();
        if(jtfNombre1.getText().equals("")||jtfAp1.getText().equals("")||jtfAm1.getText().equals("")||jtfDni2.getText().equals("")||
                (jcbDia1.getSelectedItem().equals("01")&&jcbMes1.getSelectedItem().equals("01")&&jcbAño1.getSelectedItem().equals("1940"))||
                jtfDireccion1.getText().equals("")||jtfSueldo1.getText().equals("")||jtfDniSuper1.getText().equals("")||
                jtfNoDpto1.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debes completar todos los campos");
        }else{
            String nombre = jtfNombre1.getText();
            String ap = jtfAp1.getText();
            String am = jtfAm1.getText();
            String dni = jtfDni2.getText();
            String fecha = obtenerFecha(jcbDia1, jcbMes1, jcbAño1);
            String direccion = jtfDireccion1.getText();
            String sexo = (String) jcbSexo1.getSelectedItem();
            int sueldo = Integer.parseInt(jtfSueldo1.getText());
            String dniSuper = jtfDniSuper1.getText();
            byte noDpto = Byte.parseByte(jtfNoDpto1.getText());
            
            Empleado e = new Empleado(nombre,ap,am,dni,fecha,direccion,sexo,sueldo,dniSuper,noDpto);
            
            if(eDAO.modificarRegistro(e)){
                JOptionPane.showMessageDialog(rootPane,"Datos modificados exisotosamente");
            }else{
                JOptionPane.showMessageDialog(rootPane,"No se pudieron modificar lod datos");
            }
            mostrarTabla(sqlE);
        }
    }//GEN-LAST:event_btnGuardar2ActionPerformed

    private void jcbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMesActionPerformed

    private void jcbDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDiaActionPerformed

    private void jtpContenidoABCCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpContenidoABCCKeyPressed
        mostrarTabla(sqlE);
    }//GEN-LAST:event_jtpContenidoABCCKeyPressed

    private void jtpContenidoABCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtpContenidoABCCMouseClicked
        mostrarTabla(sqlE);
    }//GEN-LAST:event_jtpContenidoABCCMouseClicked

    private void jtfNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombre2ActionPerformed

    private void jtfNombre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombre2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombre2KeyTyped

    private void jcbDia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDia2ActionPerformed

    private void jcbMes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMes2ActionPerformed

    private void jcbAño2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAño2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAño2ActionPerformed

    private void jcbSexo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSexo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSexo2ActionPerformed

    private void btnGenerarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarRActionPerformed
        Reporte r = new Reporte();
        r.mostrarReporte();
    }//GEN-LAST:event_btnGenerarRActionPerformed

    private void jtfDniSuperKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDniSuperKeyReleased
        String filtro = jtfDniSuper.getText();
        String sql =  "SELECT Dni FROM empleado WHERE Dni LIKE '"+filtro+"%'";
        mostrarTabla2(sql);
    }//GEN-LAST:event_jtfDniSuperKeyReleased

    private void jtfNoDptoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNoDptoKeyReleased
       String filtro = jtfNoDpto.getText();
       String sql = "SELECT NumeroDpto FROM departamento WHERE NumeroDpto LIKE '"+filtro+"%'";
       mostrarTabla3(sql);
    }//GEN-LAST:event_jtfNoDptoKeyReleased

    private void jtfDni1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDni1KeyReleased
        String filtro = jtfDni1.getText();
        String sql =  "SELECT * FROM empleado WHERE Dni LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfDni1KeyReleased

    private void jtfNombre1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombre1KeyReleased
        String filtro = jtfNombre1.getText();
        String sql =  "SELECT * FROM empleado WHERE Nombre LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfNombre1KeyReleased

    private void jtfAp1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAp1KeyReleased
        String filtro = jtfAp1.getText();
        String sql =  "SELECT * FROM empleado WHERE Apellido1 LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfAp1KeyReleased

    private void jtfAm1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAm1KeyReleased
        String filtro = jtfAm1.getText();
        String sql =  "SELECT * FROM empleado WHERE Apellido2 LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfAm1KeyReleased

    private void jtfDni2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDni2KeyReleased
        String filtro = jtfDni2.getText();
        String sql =  "SELECT * FROM empleado WHERE Dni LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfDni2KeyReleased

    private void jtfDireccion1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDireccion1KeyReleased
        String filtro = jtfDireccion1.getText();
        String sql =  "SELECT * FROM empleado WHERE Direccion LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfDireccion1KeyReleased

    private void jtfSueldo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSueldo1KeyReleased
        String filtro = jtfSueldo1.getText();
        String sql =  "SELECT * FROM empleado WHERE Sueldo LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfSueldo1KeyReleased

    private void jtfDniSuper1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDniSuper1KeyReleased
        String filtro = jtfDniSuper1.getText();
        String sql =  "SELECT Dni FROM empleado WHERE Dni LIKE '"+filtro+"%'";
        mostrarTabla2(sql);
    }//GEN-LAST:event_jtfDniSuper1KeyReleased

    private void jtfNoDpto1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNoDpto1KeyReleased
        String filtro = jtfNoDpto1.getText();
        String sql = "SELECT NumeroDpto FROM departamento WHERE NumeroDpto LIKE '"+filtro+"%'";
        mostrarTabla3(sql);
    }//GEN-LAST:event_jtfNoDpto1KeyReleased

    private void jtfNoDpto2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNoDpto2KeyReleased
        String filtro = jtfNoDpto2.getText();
        String sql = "SELECT NumeroDpto FROM departamento WHERE NumeroDpto LIKE '"+filtro+"%'";
        mostrarTabla3(sql);
    }//GEN-LAST:event_jtfNoDpto2KeyReleased

    private void jtfNombre2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombre2KeyReleased
        String filtro = jtfNombre2.getText();
        String sql =  "SELECT * FROM empleado WHERE Nombre LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfNombre2KeyReleased

    private void jtfAp2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAp2KeyReleased
        String filtro = jtfAp2.getText();
        String sql =  "SELECT * FROM empleado WHERE Apellido1 LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfAp2KeyReleased

    private void jtfAm2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAm2KeyReleased
        String filtro = jtfAm2.getText();
        String sql =  "SELECT * FROM empleado WHERE Apellido2 LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfAm2KeyReleased

    private void jtfDni3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDni3KeyReleased
        String filtro = jtfDni3.getText();
        String sql =  "SELECT * FROM empleado WHERE Dni LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfDni3KeyReleased

    private void jtfDireccion2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDireccion2KeyReleased
        String filtro = jtfDireccion2.getText();
        String sql =  "SELECT * FROM empleado WHERE Direccion LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfDireccion2KeyReleased

    private void jtfSueldo2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSueldo2KeyReleased
        String filtro = jtfSueldo2.getText();
        String sql =  "SELECT * FROM empleado WHERE Sueldo LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfSueldo2KeyReleased

    private void jtfDniSuper2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDniSuper2KeyReleased
        String filtro = jtfDniSuper2.getText();
        String sql =  "SELECT Dni FROM empleado WHERE Dni LIKE '"+filtro+"%'";
        mostrarTabla2(sql);
    }//GEN-LAST:event_jtfDniSuper2KeyReleased

    private void btnBorrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar3ActionPerformed
        restablecerComponentes(jtfNombre2, jtfAp2,jtfAm2, jtfDni3, jcbDia2, jcbMes2, jcbAño2, jtfDireccion2, jcbSexo2, jtfSueldo2, jtfDniSuper2, jtfNoDpto2);
    }//GEN-LAST:event_btnBorrar3ActionPerformed

    private void jtfNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyPressed
        validacionLetras(evt, jtfNombre);
    }//GEN-LAST:event_jtfNombreKeyPressed

    private void jtfApKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfApKeyPressed
        validacionLetras(evt, jtfAp);
    }//GEN-LAST:event_jtfApKeyPressed

    private void jtfAmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAmKeyPressed
        validacionLetras(evt, jtfAm);
    }//GEN-LAST:event_jtfAmKeyPressed

    private void jtfDniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDniKeyPressed
        validacionNumeros(evt, jtfDni, 10);
    }//GEN-LAST:event_jtfDniKeyPressed

    private void jtfDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDireccionKeyPressed
        validacionString(evt, jtfDireccion);
    }//GEN-LAST:event_jtfDireccionKeyPressed

    private void jtfSueldoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSueldoKeyPressed
        validacionNumeros(evt, jtfSueldo, 6);
    }//GEN-LAST:event_jtfSueldoKeyPressed

    private void jtfDniSuperKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDniSuperKeyPressed
        validacionNumeros(evt, jtfDniSuper, 10);
    }//GEN-LAST:event_jtfDniSuperKeyPressed

    private void jtfNoDptoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNoDptoKeyPressed
        validacionNumeros(evt, jtfNoDpto, 1);
    }//GEN-LAST:event_jtfNoDptoKeyPressed

    private void jtfDni1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDni1KeyPressed
        validacionNumeros(evt, jtfDni1, 10);
    }//GEN-LAST:event_jtfDni1KeyPressed

    private void jtfNombre1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombre1KeyPressed
        validacionLetras(evt, jtfNombre1);
    }//GEN-LAST:event_jtfNombre1KeyPressed

    private void jtfNombre2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombre2KeyPressed
        validacionLetras(evt, jtfNombre2);
    }//GEN-LAST:event_jtfNombre2KeyPressed

    private void jtfAp1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAp1KeyPressed
        validacionLetras(evt, jtfAp1);
    }//GEN-LAST:event_jtfAp1KeyPressed

    private void jtfAp2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAp2KeyPressed
        validacionLetras(evt, jtfAp2);
    }//GEN-LAST:event_jtfAp2KeyPressed

    private void jtfAm1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAm1KeyPressed
        validacionLetras(evt, jtfAm1);
    }//GEN-LAST:event_jtfAm1KeyPressed

    private void jtfAm2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAm2KeyPressed
        validacionLetras(evt, jtfAm2);
    }//GEN-LAST:event_jtfAm2KeyPressed

    private void jtfDni2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDni2KeyPressed
        validacionNumeros(evt, jtfDni2, 10);
    }//GEN-LAST:event_jtfDni2KeyPressed

    private void jtfDni3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDni3KeyPressed
        validacionNumeros(evt, jtfDni3, 10);
    }//GEN-LAST:event_jtfDni3KeyPressed

    private void jtfDireccion1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDireccion1KeyPressed
        validacionString(evt, jtfDireccion1);
    }//GEN-LAST:event_jtfDireccion1KeyPressed

    private void jtfDireccion2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDireccion2KeyPressed
        validacionString(evt, jtfDireccion);
    }//GEN-LAST:event_jtfDireccion2KeyPressed

    private void jtfSueldo2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSueldo2KeyPressed
        validacionNumeros(evt, jtfSueldo2, 6);
    }//GEN-LAST:event_jtfSueldo2KeyPressed

    private void jtfSueldo1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSueldo1KeyPressed
        validacionNumeros(evt, jtfSueldo1, 6);
    }//GEN-LAST:event_jtfSueldo1KeyPressed

    private void jtfDniSuper1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDniSuper1KeyPressed
        validacionNumeros(evt, jtfDniSuper1, 10);
    }//GEN-LAST:event_jtfDniSuper1KeyPressed

    private void jtfDniSuper2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDniSuper2KeyPressed
        validacionNumeros(evt, jtfDniSuper2, 10);
    }//GEN-LAST:event_jtfDniSuper2KeyPressed

    private void jtfNoDpto2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNoDpto2KeyPressed
        validacionNumeros(evt, jtfNoDpto2, 1);
    }//GEN-LAST:event_jtfNoDpto2KeyPressed

    private void jtfNoDpto1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNoDpto1KeyPressed
        validacionNumeros(evt, jtfNoDpto1, 1);
    }//GEN-LAST:event_jtfNoDpto1KeyPressed

    
    public void restablecerComponentes(Component...componentesGraficos) {
	for (Component c: componentesGraficos) {
            if (c instanceof JComboBox) {
		((JComboBox<?>)c).setSelectedIndex(0);
            }else if (c instanceof JTextField) {
		((JTextField)c).setText("");
            }
        }
    }

    
    public void mostrarTabla(String sql){
        ResultSetTableModel modeloDatos = null;
	try {
            modeloDatos = new ResultSetTableModel("com.mysql.cj.jdbc.Driver","jdbc:mysql://localhost:3306/empresa",sql);
	} catch (ClassNotFoundException e1) {
            e1.printStackTrace();
	} catch (SQLException e1) {
            e1.printStackTrace();
	}
        jScrollPane1.getViewport().remove(jTable1);
        jTable1 = new JTable(modeloDatos);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                obtenerRegistroTabla();
            }
        });
        jScrollPane1.getViewport().add(jTable1);
        
    }
    
    
    public void obtenerRegistroTabla(){
        jtfNombre1.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),0));
        jtfAp1.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),1));
        jtfAm1.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),2));
        jtfDni1.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),3));
        jtfDni2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),3));
        
        jtfDireccion1.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),5));
       
        jtfSueldo1.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),7));
        jtfDniSuper1.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),8));
        jtfNoDpto1.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),9));
    }
    
    public String obtenerFecha(JComboBox dia,JComboBox mes,JComboBox año){
        String d = (String) dia.getSelectedItem();
        String m = (String) mes.getSelectedItem();
        String a = (String) año.getSelectedItem();
        return a+"-"+m+"-"+d;
    }
    
    public void validacionLetras(KeyEvent evt, JTextField jtf){  
        char car = evt.getKeyChar();
	if(Character.isLetter(car)||(car==KeyEvent.VK_BACK_SPACE)){
            jtf.setEditable(true);
        }else{
            jtf.setEditable(false);
        }
    }
    
    public void validacionNumeros(KeyEvent evt, JTextField jtf, int lim){
        int code=evt.getKeyCode();    
        if (((evt.getKeyChar() >= '0'&&evt.getKeyChar() <= '9'))&&jtf.getText().length()<lim||(code==KeyEvent.VK_BACK_SPACE)) {
            jtf.setEditable(true);
        }else{
            jtf.setEditable(false);
        }  
    }
    
    public void validacionString(KeyEvent evt, JTextField jtf){
        int code = evt.getKeyCode();
        int limite = 20;
        if ((jtf.getText().equals("")?true:!(jtf.getText().charAt(jtf.getText().length()-1)==' '&&code==KeyEvent.VK_SPACE))&&(jtf.getText().length()<limite||code==KeyEvent.VK_BACK_SPACE)) {
                jtf.setEditable(true);
        }else{
                jtf.setEditable(false);
        }
    }
    
    
    public void mostrarTabla2(String sql){
        ResultSetTableModel modeloDatos = null;
	try {
            modeloDatos = new ResultSetTableModel("com.mysql.cj.jdbc.Driver","jdbc:mysql://localhost:3306/empresa",sql);
	} catch (ClassNotFoundException e1) {
            e1.printStackTrace();
	} catch (SQLException e1) {
            e1.printStackTrace();
	}
        jScrollPane2.getViewport().remove(jTable2);
        jTable2 = new JTable(modeloDatos);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                obtenerRegistroTabla2();
            }
        });
        jScrollPane2.getViewport().add(jTable2);
    }    
    public void obtenerRegistroTabla2(){
        jtfDniSuper.setText(""+jTable2.getValueAt(jTable2.getSelectedRow(),0));
        jtfDniSuper1.setText(""+jTable2.getValueAt(jTable2.getSelectedRow(),0));
        jtfDniSuper2.setText(""+jTable2.getValueAt(jTable2.getSelectedRow(),0));
    }
    
    
    public void mostrarTabla3(String sql){
        ResultSetTableModel modeloDatos = null;
	try {
            modeloDatos = new ResultSetTableModel("com.mysql.cj.jdbc.Driver","jdbc:mysql://localhost:3306/empresa",sql);
	} catch (ClassNotFoundException e1) {
            e1.printStackTrace();
	} catch (SQLException e1) {
            e1.printStackTrace();
	}
        jScrollPane3.getViewport().remove(jTable3);
        jTable3 = new JTable(modeloDatos);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                obtenerRegistroTabla3();
            }
        });
        jScrollPane3.getViewport().add(jTable3);
    }    
    public void obtenerRegistroTabla3(){
        jtfNoDpto.setText(""+jTable3.getValueAt(jTable3.getSelectedRow(),0));
        jtfNoDpto1.setText(""+jTable3.getValueAt(jTable3.getSelectedRow(),0));
        jtfNoDpto2.setText(""+jTable3.getValueAt(jTable3.getSelectedRow(),0));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoM;
    private javax.swing.JLabel ApellidoM1;
    private javax.swing.JLabel ApellidoM2;
    private javax.swing.JLabel ApellidoP;
    private javax.swing.JLabel ApellidoP1;
    private javax.swing.JLabel ApellidoP2;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Direccion1;
    private javax.swing.JLabel Direccion2;
    private javax.swing.JLabel Dni;
    private javax.swing.JLabel Dni1;
    private javax.swing.JLabel Dni2;
    private javax.swing.JLabel Dni3;
    private javax.swing.JLabel DniSuper;
    private javax.swing.JLabel DniSuper1;
    private javax.swing.JLabel DniSuper2;
    private javax.swing.JLabel FechaNac;
    private javax.swing.JLabel FechaNac1;
    private javax.swing.JLabel FechaNac2;
    private javax.swing.JLabel NoDpto;
    private javax.swing.JLabel NoDpto1;
    private javax.swing.JLabel NoDpto2;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Sexo;
    private javax.swing.JLabel Sexo1;
    private javax.swing.JLabel Sexo2;
    private javax.swing.JLabel Sueldo;
    private javax.swing.JLabel Sueldo1;
    private javax.swing.JLabel Sueldo2;
    private javax.swing.JLabel TabDniS;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel Titulo3;
    private javax.swing.JLabel Titulo4;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrar1;
    private javax.swing.JButton btnBorrar2;
    private javax.swing.JButton btnBorrar3;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerarR;
    private javax.swing.JButton btnGuardar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JComboBox<String> jcbAño;
    private javax.swing.JComboBox<String> jcbAño1;
    private javax.swing.JComboBox<String> jcbAño2;
    private javax.swing.JComboBox<String> jcbDia;
    private javax.swing.JComboBox<String> jcbDia1;
    private javax.swing.JComboBox<String> jcbDia2;
    private javax.swing.JComboBox<String> jcbMes;
    private javax.swing.JComboBox<String> jcbMes1;
    private javax.swing.JComboBox<String> jcbMes2;
    private javax.swing.JComboBox<String> jcbSexo;
    private javax.swing.JComboBox<String> jcbSexo1;
    private javax.swing.JComboBox<String> jcbSexo2;
    private javax.swing.JPanel jpAltas;
    private javax.swing.JPanel jpBajas;
    private javax.swing.JPanel jpCambios;
    private javax.swing.JPanel jpConsultas;
    private javax.swing.JPanel jpTabla;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JTextField jtfAm;
    private javax.swing.JTextField jtfAm1;
    private javax.swing.JTextField jtfAm2;
    private javax.swing.JTextField jtfAp;
    private javax.swing.JTextField jtfAp1;
    private javax.swing.JTextField jtfAp2;
    private javax.swing.JTextField jtfDireccion;
    private javax.swing.JTextField jtfDireccion1;
    private javax.swing.JTextField jtfDireccion2;
    private javax.swing.JTextField jtfDni;
    private javax.swing.JTextField jtfDni1;
    private javax.swing.JTextField jtfDni2;
    private javax.swing.JTextField jtfDni3;
    private javax.swing.JTextField jtfDniSuper;
    private javax.swing.JTextField jtfDniSuper1;
    private javax.swing.JTextField jtfDniSuper2;
    private javax.swing.JTextField jtfNoDpto;
    private javax.swing.JTextField jtfNoDpto1;
    private javax.swing.JTextField jtfNoDpto2;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfNombre1;
    private javax.swing.JTextField jtfNombre2;
    private javax.swing.JTextField jtfSueldo;
    private javax.swing.JTextField jtfSueldo1;
    private javax.swing.JTextField jtfSueldo2;
    private javax.swing.JTabbedPane jtpContenidoABCC;
    // End of variables declaration//GEN-END:variables
}
