/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author clara
 */
public class MenuEmpleado extends javax.swing.JPanel {
     Color c1 = new Color(162,65,107);
     Color c2 = new Color(190,65,100);
    /**
     * Creates new form MenuEmpleado
     */
    public MenuEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAltasEmp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnBajasEmp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnConsultasEmp = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnCambiosEmp = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(960, 100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAltasEmp.setBackground(new java.awt.Color(162, 65, 107));
        btnAltasEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAltasEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltasEmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAltasEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAltasEmpMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Altas");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btnAltasEmpLayout = new javax.swing.GroupLayout(btnAltasEmp);
        btnAltasEmp.setLayout(btnAltasEmpLayout);
        btnAltasEmpLayout.setHorizontalGroup(
            btnAltasEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAltasEmpLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel3)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        btnAltasEmpLayout.setVerticalGroup(
            btnAltasEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAltasEmpLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        add(btnAltasEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 100));

        btnBajasEmp.setBackground(new java.awt.Color(162, 65, 107));
        btnBajasEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBajasEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBajasEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBajasEmpMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bajas");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btnBajasEmpLayout = new javax.swing.GroupLayout(btnBajasEmp);
        btnBajasEmp.setLayout(btnBajasEmpLayout);
        btnBajasEmpLayout.setHorizontalGroup(
            btnBajasEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBajasEmpLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel4)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        btnBajasEmpLayout.setVerticalGroup(
            btnBajasEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBajasEmpLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        add(btnBajasEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 240, 100));

        btnConsultasEmp.setBackground(new java.awt.Color(162, 65, 107));
        btnConsultasEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultasEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultasEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultasEmpMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Consultas");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btnConsultasEmpLayout = new javax.swing.GroupLayout(btnConsultasEmp);
        btnConsultasEmp.setLayout(btnConsultasEmpLayout);
        btnConsultasEmpLayout.setHorizontalGroup(
            btnConsultasEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConsultasEmpLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(76, 76, 76))
        );
        btnConsultasEmpLayout.setVerticalGroup(
            btnConsultasEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConsultasEmpLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(btnConsultasEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 240, 100));

        btnCambiosEmp.setBackground(new java.awt.Color(162, 65, 107));
        btnCambiosEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiosEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCambiosEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCambiosEmpMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cambios");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btnCambiosEmpLayout = new javax.swing.GroupLayout(btnCambiosEmp);
        btnCambiosEmp.setLayout(btnCambiosEmpLayout);
        btnCambiosEmpLayout.setHorizontalGroup(
            btnCambiosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCambiosEmpLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(76, 76, 76))
        );
        btnCambiosEmpLayout.setVerticalGroup(
            btnCambiosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCambiosEmpLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(btnCambiosEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 240, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltasEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltasEmpMouseEntered
        btnAltasEmp.setBackground(c2);
    }//GEN-LAST:event_btnAltasEmpMouseEntered

    private void btnAltasEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltasEmpMouseExited
        btnAltasEmp.setBackground(c1);
    }//GEN-LAST:event_btnAltasEmpMouseExited

    private void btnBajasEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBajasEmpMouseEntered
        btnBajasEmp.setBackground(c2);
    }//GEN-LAST:event_btnBajasEmpMouseEntered

    private void btnBajasEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBajasEmpMouseExited
        btnBajasEmp.setBackground(c1);
    }//GEN-LAST:event_btnBajasEmpMouseExited

    private void btnCambiosEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiosEmpMouseEntered
        btnCambiosEmp.setBackground(c2);
    }//GEN-LAST:event_btnCambiosEmpMouseEntered

    private void btnCambiosEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiosEmpMouseExited
        btnCambiosEmp.setBackground(c1);
    }//GEN-LAST:event_btnCambiosEmpMouseExited

    private void btnConsultasEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultasEmpMouseEntered
        btnConsultasEmp.setBackground(c2);
    }//GEN-LAST:event_btnConsultasEmpMouseEntered

    private void btnConsultasEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultasEmpMouseExited
        btnConsultasEmp.setBackground(c1);
    }//GEN-LAST:event_btnConsultasEmpMouseExited

    private void btnAltasEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltasEmpMouseClicked
        AltasEmpleado ae = new AltasEmpleado();
        mostrarPanelContenido(ae);
    }//GEN-LAST:event_btnAltasEmpMouseClicked

    
    private void mostrarPanelContenido (JPanel p){
        p.setSize(960, 600);
        p.setLocation(0, 0);
        
        vp.getJpContenido().removeAll();
        vp.getJpContenido().add(p, BorderLayout.CENTER);
        vp.getJpContenido().revalidate();
        vp.getJpContenido().repaint();
       
    }

    VentanaPrincipal vp = new VentanaPrincipal();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAltasEmp;
    private javax.swing.JPanel btnBajasEmp;
    private javax.swing.JPanel btnCambiosEmp;
    private javax.swing.JPanel btnConsultasEmp;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
