/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import contolador.ProyectoDAO;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import modelo.Proyecto;
import modelo.Grafica;



/**
 *
 * @author clara
 */
public class MenuProyecto extends javax.swing.JPanel {

    private Component rootPane;
    String sqlP = "SELECT * FROM proyecto";

    /**
     * Creates new form MenuEmpleado1
     */
    public MenuProyecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtpContenidoABCC = new javax.swing.JTabbedPane();
        jpAltas = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        NomProyecto = new javax.swing.JLabel();
        jtfNomProyecto = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        NumProyecto = new javax.swing.JLabel();
        jtfNumProyecto = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        UbiProyecto = new javax.swing.JLabel();
        jtfUbiProyecto = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        NumDptoProyecto = new javax.swing.JLabel();
        jtfNumDptoProyecto = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        btnAgregar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        NumDptoProyecto1 = new javax.swing.JLabel();
        jpBajas = new javax.swing.JPanel();
        Titulo1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        NumProyecto1 = new javax.swing.JLabel();
        jtfNumProyecto1 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        btnBuscar1 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBorrar1 = new javax.swing.JButton();
        jpCambios = new javax.swing.JPanel();
        Titulo2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        NomProyecto2 = new javax.swing.JLabel();
        jtfNomProyecto2 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        NumProyecto2 = new javax.swing.JLabel();
        jtfNumProyecto2 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        UbiProyecto2 = new javax.swing.JLabel();
        jtfUbiProyecto2 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        NumDptoProyecto2 = new javax.swing.JLabel();
        jtfNumDptoProyecto2 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        btnBuscar2 = new javax.swing.JButton();
        btnGuardar2 = new javax.swing.JButton();
        btnBorrar2 = new javax.swing.JButton();
        NumDptoProyecto4 = new javax.swing.JLabel();
        jpConsultas = new javax.swing.JPanel();
        Titulo3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        NomProyecto3 = new javax.swing.JLabel();
        jtfNomProyecto3 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        NumProyecto3 = new javax.swing.JLabel();
        jtfNumProyecto3 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        UbiProyecto3 = new javax.swing.JLabel();
        jtfUbiProyecto3 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        NumDptoProyecto3 = new javax.swing.JLabel();
        jtfNumDptoProyecto3 = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        btnBorrar3 = new javax.swing.JButton();
        jpGrafica = new javax.swing.JPanel();
        btnGenerarG = new javax.swing.JButton();
        jpTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        TabLoc = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 198, 165));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setBackground(new java.awt.Color(162, 65, 107));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Proyecto");

        javax.swing.GroupLayout jpTituloLayout = new javax.swing.GroupLayout(jpTitulo);
        jpTitulo.setLayout(jpTituloLayout);
        jpTituloLayout.setHorizontalGroup(
            jpTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(836, Short.MAX_VALUE))
        );
        jpTituloLayout.setVerticalGroup(
            jpTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTituloLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );

        add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 100));

        jtpContenidoABCC.setBackground(new java.awt.Color(245, 198, 165));
        jtpContenidoABCC.setForeground(new java.awt.Color(102, 102, 102));
        jtpContenidoABCC.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jtpContenidoABCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtpContenidoABCCMouseClicked(evt);
            }
        });

        jpAltas.setBackground(new java.awt.Color(245, 198, 165));
        jpAltas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Agregar proyecto");
        jpAltas.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 30, 500, 41));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 840, 21));

        NomProyecto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NomProyecto.setForeground(new java.awt.Color(102, 102, 102));
        NomProyecto.setText("Nombre del proyecto");
        jpAltas.add(NomProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 30));

        jtfNomProyecto.setBackground(new java.awt.Color(245, 198, 165));
        jtfNomProyecto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfNomProyecto.setBorder(null);
        jtfNomProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomProyectoActionPerformed(evt);
            }
        });
        jtfNomProyecto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNomProyectoKeyPressed(evt);
            }
        });
        jpAltas.add(jtfNomProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 159, 30));
        jpAltas.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 159, 20));

        NumProyecto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NumProyecto.setForeground(new java.awt.Color(102, 102, 102));
        NumProyecto.setText("Número de proyecto");
        jpAltas.add(NumProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, 30));

        jtfNumProyecto.setBackground(new java.awt.Color(245, 198, 165));
        jtfNumProyecto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfNumProyecto.setBorder(null);
        jtfNumProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumProyectoActionPerformed(evt);
            }
        });
        jtfNumProyecto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNumProyectoKeyPressed(evt);
            }
        });
        jpAltas.add(jtfNumProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 50, 30));
        jpAltas.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 50, 20));

        UbiProyecto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        UbiProyecto.setForeground(new java.awt.Color(102, 102, 102));
        UbiProyecto.setText("Ubicación del proyecto");
        jpAltas.add(UbiProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 30));

        jtfUbiProyecto.setEditable(false);
        jtfUbiProyecto.setBackground(new java.awt.Color(245, 198, 165));
        jtfUbiProyecto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfUbiProyecto.setBorder(null);
        jpAltas.add(jtfUbiProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 159, 30));
        jpAltas.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 159, 20));

        NumDptoProyecto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NumDptoProyecto.setForeground(new java.awt.Color(102, 102, 102));
        NumDptoProyecto.setText("Número de departamento del proyecto");
        jpAltas.add(NumDptoProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, 30));

        jtfNumDptoProyecto.setEditable(false);
        jtfNumDptoProyecto.setBackground(new java.awt.Color(245, 198, 165));
        jtfNumDptoProyecto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfNumDptoProyecto.setBorder(null);
        jpAltas.add(jtfNumDptoProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 50, 30));
        jpAltas.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 50, 20));

        btnAgregar.setBackground(new java.awt.Color(162, 65, 107));
        btnAgregar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jpAltas.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 120, 30));

        btnBorrar.setBackground(new java.awt.Color(162, 65, 107));
        btnBorrar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(null);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jpAltas.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 120, 30));

        NumDptoProyecto1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        NumDptoProyecto1.setForeground(new java.awt.Color(102, 102, 102));
        NumDptoProyecto1.setText("La ubicación y número de departamento deben ser selecionados de la tabla localizaciones");
        jpAltas.add(NumDptoProyecto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, 30));

        jtpContenidoABCC.addTab("Altas", jpAltas);

        jpBajas.setBackground(new java.awt.Color(245, 198, 165));
        jpBajas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo1.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setText("Eliminar proyecto");
        jpBajas.add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 30, 500, 41));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jpBajas.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 840, 21));

        NumProyecto1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NumProyecto1.setForeground(new java.awt.Color(102, 102, 102));
        NumProyecto1.setText("Número de proyecto");
        jpBajas.add(NumProyecto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 30));

        jtfNumProyecto1.setBackground(new java.awt.Color(245, 198, 165));
        jtfNumProyecto1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfNumProyecto1.setBorder(null);
        jtfNumProyecto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumProyecto1ActionPerformed(evt);
            }
        });
        jpBajas.add(jtfNumProyecto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 50, 30));
        jpBajas.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 50, 20));

        btnBuscar1.setBackground(new java.awt.Color(162, 65, 107));
        btnBuscar1.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar1.setText("Buscar");
        btnBuscar1.setBorder(null);
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        jpBajas.add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 120, 30));

        btnEliminar.setBackground(new java.awt.Color(162, 65, 107));
        btnEliminar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jpBajas.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 120, 30));

        btnBorrar1.setBackground(new java.awt.Color(162, 65, 107));
        btnBorrar1.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBorrar1.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar1.setText("Borrar");
        btnBorrar1.setBorder(null);
        btnBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar1ActionPerformed(evt);
            }
        });
        jpBajas.add(btnBorrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 120, 30));

        jtpContenidoABCC.addTab("Bajas", jpBajas);

        jpCambios.setBackground(new java.awt.Color(245, 198, 165));
        jpCambios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo2.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo2.setForeground(new java.awt.Color(255, 255, 255));
        Titulo2.setText("Modificar proyecto");
        jpCambios.add(Titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 30, 500, 41));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 840, 21));

        NomProyecto2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NomProyecto2.setForeground(new java.awt.Color(102, 102, 102));
        NomProyecto2.setText("Nombre del proyecto");
        jpCambios.add(NomProyecto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 30));

        jtfNomProyecto2.setBackground(new java.awt.Color(245, 198, 165));
        jtfNomProyecto2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfNomProyecto2.setBorder(null);
        jpCambios.add(jtfNomProyecto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 159, 30));
        jpCambios.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 159, 20));

        NumProyecto2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NumProyecto2.setForeground(new java.awt.Color(102, 102, 102));
        NumProyecto2.setText("Número de proyecto");
        jpCambios.add(NumProyecto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, 30));

        jtfNumProyecto2.setBackground(new java.awt.Color(245, 198, 165));
        jtfNumProyecto2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfNumProyecto2.setBorder(null);
        jtfNumProyecto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumProyecto2ActionPerformed(evt);
            }
        });
        jpCambios.add(jtfNumProyecto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 50, 30));
        jpCambios.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 50, 20));

        UbiProyecto2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        UbiProyecto2.setForeground(new java.awt.Color(102, 102, 102));
        UbiProyecto2.setText("Ubicación del proyecto");
        jpCambios.add(UbiProyecto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 30));

        jtfUbiProyecto2.setEditable(false);
        jtfUbiProyecto2.setBackground(new java.awt.Color(245, 198, 165));
        jtfUbiProyecto2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfUbiProyecto2.setBorder(null);
        jpCambios.add(jtfUbiProyecto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 159, 30));
        jpCambios.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 159, 20));

        NumDptoProyecto2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NumDptoProyecto2.setForeground(new java.awt.Color(102, 102, 102));
        NumDptoProyecto2.setText("Número de departamento del proyecto");
        jpCambios.add(NumDptoProyecto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, 30));

        jtfNumDptoProyecto2.setEditable(false);
        jtfNumDptoProyecto2.setBackground(new java.awt.Color(245, 198, 165));
        jtfNumDptoProyecto2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfNumDptoProyecto2.setBorder(null);
        jpCambios.add(jtfNumDptoProyecto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 50, 30));
        jpCambios.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 50, 20));

        btnBuscar2.setBackground(new java.awt.Color(162, 65, 107));
        btnBuscar2.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBuscar2.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar2.setText("Buscar");
        btnBuscar2.setBorder(null);
        btnBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar2ActionPerformed(evt);
            }
        });
        jpCambios.add(btnBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 120, 30));

        btnGuardar2.setBackground(new java.awt.Color(162, 65, 107));
        btnGuardar2.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnGuardar2.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar2.setText("Guardar cambios");
        btnGuardar2.setBorder(null);
        btnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar2ActionPerformed(evt);
            }
        });
        jpCambios.add(btnGuardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 160, 30));

        btnBorrar2.setBackground(new java.awt.Color(162, 65, 107));
        btnBorrar2.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBorrar2.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar2.setText("Borrar");
        btnBorrar2.setBorder(null);
        btnBorrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar2ActionPerformed(evt);
            }
        });
        jpCambios.add(btnBorrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 120, 30));

        NumDptoProyecto4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        NumDptoProyecto4.setForeground(new java.awt.Color(102, 102, 102));
        NumDptoProyecto4.setText("La ubicación y número de departamento deben ser selecionados de la tabla localizaciones");
        jpCambios.add(NumDptoProyecto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 30));

        jtpContenidoABCC.addTab("Cambios", jpCambios);

        jpConsultas.setBackground(new java.awt.Color(245, 198, 165));
        jpConsultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo3.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo3.setForeground(new java.awt.Color(255, 255, 255));
        Titulo3.setText("Buscar");
        jpConsultas.add(Titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 500, 41));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 840, 21));

        NomProyecto3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NomProyecto3.setForeground(new java.awt.Color(102, 102, 102));
        NomProyecto3.setText("Nombre del proyecto");
        jpConsultas.add(NomProyecto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        jtfNomProyecto3.setBackground(new java.awt.Color(245, 198, 165));
        jtfNomProyecto3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfNomProyecto3.setBorder(null);
        jtfNomProyecto3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNomProyecto3KeyReleased(evt);
            }
        });
        jpConsultas.add(jtfNomProyecto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 159, 30));
        jpConsultas.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 159, 20));

        NumProyecto3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NumProyecto3.setForeground(new java.awt.Color(102, 102, 102));
        NumProyecto3.setText("Número de proyecto");
        jpConsultas.add(NumProyecto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, 30));

        jtfNumProyecto3.setBackground(new java.awt.Color(245, 198, 165));
        jtfNumProyecto3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfNumProyecto3.setBorder(null);
        jtfNumProyecto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumProyecto3ActionPerformed(evt);
            }
        });
        jtfNumProyecto3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNumProyecto3KeyReleased(evt);
            }
        });
        jpConsultas.add(jtfNumProyecto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 50, 30));
        jpConsultas.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 50, 20));

        UbiProyecto3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        UbiProyecto3.setForeground(new java.awt.Color(102, 102, 102));
        UbiProyecto3.setText("Ubicación del proyecto");
        jpConsultas.add(UbiProyecto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 30));

        jtfUbiProyecto3.setBackground(new java.awt.Color(245, 198, 165));
        jtfUbiProyecto3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfUbiProyecto3.setBorder(null);
        jtfUbiProyecto3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfUbiProyecto3KeyReleased(evt);
            }
        });
        jpConsultas.add(jtfUbiProyecto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 159, 30));
        jpConsultas.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 159, 20));

        NumDptoProyecto3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NumDptoProyecto3.setForeground(new java.awt.Color(102, 102, 102));
        NumDptoProyecto3.setText("Número de departamento del proyecto");
        jpConsultas.add(NumDptoProyecto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, 30));

        jtfNumDptoProyecto3.setBackground(new java.awt.Color(245, 198, 165));
        jtfNumDptoProyecto3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfNumDptoProyecto3.setBorder(null);
        jtfNumDptoProyecto3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNumDptoProyecto3KeyReleased(evt);
            }
        });
        jpConsultas.add(jtfNumDptoProyecto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 50, 30));
        jpConsultas.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 50, 20));

        btnBorrar3.setBackground(new java.awt.Color(162, 65, 107));
        btnBorrar3.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBorrar3.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar3.setText("Borrar");
        btnBorrar3.setBorder(null);
        btnBorrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar3ActionPerformed(evt);
            }
        });
        jpConsultas.add(btnBorrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 120, 30));

        jtpContenidoABCC.addTab("Consultas", jpConsultas);

        jpGrafica.setBackground(new java.awt.Color(245, 198, 165));
        jpGrafica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGenerarG.setBackground(new java.awt.Color(162, 65, 107));
        btnGenerarG.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnGenerarG.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarG.setText("Generar gráfica");
        btnGenerarG.setBorder(null);
        btnGenerarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarGActionPerformed(evt);
            }
        });
        jpGrafica.add(btnGenerarG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 140, 40));

        jtpContenidoABCC.addTab("Gráfica", jpGrafica);

        add(jtpContenidoABCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 960, 330));

        jpTabla.setBackground(new java.awt.Color(255, 255, 255));
        jpTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jpTabla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 610, 230));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jpTabla.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 250, 200));

        TabLoc.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        TabLoc.setForeground(new java.awt.Color(102, 102, 102));
        TabLoc.setText("Tabla localizaciones");
        jpTabla.add(TabLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 150, 20));

        add(jpTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 960, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        String sql =  "SELECT * FROM proyecto WHERE NumProyecto = '"+jtfNumProyecto1.getText()+"'";
        if(jtfNumProyecto1.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar el numero de proyecto");
        }else{
            mostrarTabla(sql);
        }
        
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       
        ProyectoDAO pDAO = new ProyectoDAO();
        if(jtfNumProyecto1.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane,"Debes ingresar el número de proyecto");
	}else {
             byte num = Byte.parseByte(jtfNumProyecto1.getText());
            if(pDAO.eliminarRegistro(num)) {
                JOptionPane.showMessageDialog(rootPane,"Se eliminó correctamente de la base de datos");
            }else{
                 JOptionPane.showMessageDialog(rootPane,"Hubo un error al intentar eliminar a la base de datos");
            }
           
	}
        mostrarTabla(sqlP);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar2ActionPerformed
        String sql =  "SELECT * FROM proyecto WHERE NumProyecto = '"+jtfNumProyecto2.getText()+"'";
        if(jtfNumProyecto2.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar el numero de proyecto");
        }else{
            mostrarTabla(sql);
        }
    }//GEN-LAST:event_btnBuscar2ActionPerformed

    private void btnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar2ActionPerformed
        ProyectoDAO pDAO = new ProyectoDAO();
        if(jtfNomProyecto2.getText().equals("")||jtfNumProyecto2.getText().equals("")||
                jtfUbiProyecto2.getText().equals("")||jtfNumDptoProyecto2.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debes completar los campos");
        }else{
            Proyecto p = new Proyecto(jtfNomProyecto2.getText(),Integer.parseInt(jtfNumProyecto2.getText()),
            jtfUbiProyecto2.getText(),Byte.parseByte(jtfNumDptoProyecto2.getText()));
            if(pDAO.modificarRegistro(p)){
                JOptionPane.showMessageDialog(rootPane, "Datos modificados exitosamente");
            }else{
                JOptionPane.showMessageDialog(rootPane, "No se pudieron modificar los datos");
            }
            mostrarTabla(sqlP);
        }
    }//GEN-LAST:event_btnGuardar2ActionPerformed

    private void btnBorrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar2ActionPerformed
        restablecerComponentes(jtfNomProyecto2,jtfNumProyecto2,jtfUbiProyecto2,jtfNumDptoProyecto2);
    }//GEN-LAST:event_btnBorrar2ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        restablecerComponentes(jtfNomProyecto,jtfNumProyecto,jtfUbiProyecto,jtfNumDptoProyecto);
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void jtfNumProyecto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumProyecto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumProyecto1ActionPerformed

    private void jtfNumProyecto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumProyecto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumProyecto2ActionPerformed

    private void btnBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar1ActionPerformed
        restablecerComponentes(jtfNumProyecto1);
    }//GEN-LAST:event_btnBorrar1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        ProyectoDAO pDAO = new ProyectoDAO();
        if(jtfNomProyecto.getText().equals("")||jtfNumProyecto.getText().equals("")||
                jtfUbiProyecto.getText().equals("")||jtfNumDptoProyecto.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debes completar los campos");
        }else{
            Proyecto p = new Proyecto(jtfNomProyecto.getText(),Integer.parseInt(jtfNumProyecto.getText()),
            jtfUbiProyecto.getText(),Byte.parseByte(jtfNumDptoProyecto.getText()));
            
            if(pDAO.insertarRragistro(p)){
                JOptionPane.showMessageDialog(rootPane,"Se agregó correctamente a la base de datos");
            }else{
                JOptionPane.showMessageDialog(rootPane,"Hubo un error al intentar agregar a la base de datos");
            }
            
        }
        mostrarTabla(sqlP);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jtfNumProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumProyectoActionPerformed

    private void jtfNomProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomProyectoActionPerformed
        //if ((ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9')||(code==KeyEvent.VK_BACK_SPACE)) {}
        
    }//GEN-LAST:event_jtfNomProyectoActionPerformed

    private void jtpContenidoABCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtpContenidoABCCMouseClicked
        mostrarTabla(sqlP);
    }//GEN-LAST:event_jtpContenidoABCCMouseClicked

    private void jtfNomProyectoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomProyectoKeyPressed
        validacionLetras(evt,jtfNomProyecto);
    }//GEN-LAST:event_jtfNomProyectoKeyPressed

    private void jtfNumProyectoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNumProyectoKeyPressed
        validacionNumeros(evt, jtfNumProyecto);
    }//GEN-LAST:event_jtfNumProyectoKeyPressed

    private void jtfNumProyecto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumProyecto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumProyecto3ActionPerformed

    private void jtfNomProyecto3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomProyecto3KeyReleased
        String filtro = jtfNomProyecto3.getText();
        String sql =  "SELECT * FROM proyecto WHERE NombreProyecto LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfNomProyecto3KeyReleased

    private void jtfNumProyecto3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNumProyecto3KeyReleased
        String filtro = jtfNumProyecto3.getText();
        String sql =  "SELECT * FROM proyecto WHERE NumProyecto LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfNumProyecto3KeyReleased

    private void btnGenerarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarGActionPerformed
       Grafica g = new Grafica();
     
       if(g.dibujar()!=null){
           jpGrafica.setLayout(new BorderLayout());
           jpGrafica.add(g.dibujar(),new BorderLayout().NORTH);
           
       }else{
           System.out.println("No funciona");
       }
        
    }//GEN-LAST:event_btnGenerarGActionPerformed

    private void jtfUbiProyecto3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfUbiProyecto3KeyReleased
        String filtro = jtfUbiProyecto3.getText();
        String sql =  "SELECT * FROM proyecto WHERE UbicacionProyecto LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfUbiProyecto3KeyReleased

    private void jtfNumDptoProyecto3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNumDptoProyecto3KeyReleased
        String filtro = jtfNumDptoProyecto3.getText();
        String sql =  "SELECT * FROM proyecto WHERE NumDptoProyecto LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfNumDptoProyecto3KeyReleased

    private void btnBorrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar3ActionPerformed
        restablecerComponentes(jtfNomProyecto3,jtfNumProyecto3,jtfUbiProyecto3,jtfNumDptoProyecto3);
    }//GEN-LAST:event_btnBorrar3ActionPerformed

    
    
    public void restablecerComponentes(Component...componentesGraficos) {
	for (Component c: componentesGraficos) {
            if (c instanceof JTextField) {
		((JTextField)c).setText("");
            }
        }
    }
    
    public void mostrarTabla(String sql){
        ResultSetTableModel modeloDatos = null;
	try {
            modeloDatos = new ResultSetTableModel("com.mysql.cj.jdbc.Driver","jdbc:mysql://localhost:3306/empresa",sql);
	} catch (ClassNotFoundException e1) {
            e1.printStackTrace();
	} catch (SQLException e1) {
            e1.printStackTrace();
	}
        jScrollPane1.getViewport().remove(jTable1);
        jTable1 = new JTable(modeloDatos);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                obtenerRegistroTabla();
            }
        });
        jScrollPane1.getViewport().add(jTable1);
        
    }
    
    
    public void obtenerRegistroTabla(){
        jtfNomProyecto2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),0));
        jtfNomProyecto3.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),0));
        jtfNumProyecto1.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),1));
        jtfNumProyecto2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),1));
        jtfNumProyecto3.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),1));
        jtfUbiProyecto2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),2));
        jtfUbiProyecto3.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),2));
        jtfNumDptoProyecto2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),3));
        jtfNumDptoProyecto3.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),3));
        
    }
    
    public void mostrarTabla2(){
        ResultSetTableModel modeloDatos = null;
	try {
            modeloDatos = new ResultSetTableModel("com.mysql.cj.jdbc.Driver","jdbc:mysql://localhost:3306/empresa","SELECT * FROM localizaciones_dpto");
	} catch (ClassNotFoundException e1) {
            e1.printStackTrace();
	} catch (SQLException e1) {
            e1.printStackTrace();
	}
        jScrollPane2.getViewport().remove(jTable2);
        jTable2 = new JTable(modeloDatos);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                obtenerRegistroTabla2();
            }
        });
        jScrollPane2.getViewport().add(jTable2);
        
    }
    public void obtenerRegistroTabla2(){
        jtfUbiProyecto.setText(""+jTable2.getValueAt(jTable2.getSelectedRow(),1));
        jtfUbiProyecto2.setText(""+jTable2.getValueAt(jTable2.getSelectedRow(),1));
        jtfNumDptoProyecto.setText(""+jTable2.getValueAt(jTable2.getSelectedRow(),0));
        jtfNumDptoProyecto2.setText(""+jTable2.getValueAt(jTable2.getSelectedRow(),0));
        
    }
    
    public void validacionLetras(KeyEvent evt, JTextField jtf){
        int code = evt.getKeyCode();
        int limite = 20;
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')) {
            jtf.setEditable(false);
	}else{
            jtf.setEditable(true);
	}
    }
    
    public void validacionNumeros(KeyEvent evt, JTextField jtf){
        int code=evt.getKeyCode();
        int limite=3;    
        if (((evt.getKeyChar() >= '0'&&evt.getKeyChar() <= '9'))&&jtf.getText().length()<limite||(code==KeyEvent.VK_BACK_SPACE)) {
            jtf.setEditable(true);
        }else{
            jtf.setEditable(false);
        }  
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NomProyecto;
    private javax.swing.JLabel NomProyecto2;
    private javax.swing.JLabel NomProyecto3;
    private javax.swing.JLabel NumDptoProyecto;
    private javax.swing.JLabel NumDptoProyecto1;
    private javax.swing.JLabel NumDptoProyecto2;
    private javax.swing.JLabel NumDptoProyecto3;
    private javax.swing.JLabel NumDptoProyecto4;
    private javax.swing.JLabel NumProyecto;
    private javax.swing.JLabel NumProyecto1;
    private javax.swing.JLabel NumProyecto2;
    private javax.swing.JLabel NumProyecto3;
    private javax.swing.JLabel TabLoc;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel Titulo3;
    private javax.swing.JLabel UbiProyecto;
    private javax.swing.JLabel UbiProyecto2;
    private javax.swing.JLabel UbiProyecto3;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrar1;
    private javax.swing.JButton btnBorrar2;
    private javax.swing.JButton btnBorrar3;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerarG;
    private javax.swing.JButton btnGuardar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel jpAltas;
    private javax.swing.JPanel jpBajas;
    private javax.swing.JPanel jpCambios;
    private javax.swing.JPanel jpConsultas;
    private javax.swing.JPanel jpGrafica;
    private javax.swing.JPanel jpTabla;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JTextField jtfNomProyecto;
    private javax.swing.JTextField jtfNomProyecto2;
    private javax.swing.JTextField jtfNomProyecto3;
    private javax.swing.JTextField jtfNumDptoProyecto;
    private javax.swing.JTextField jtfNumDptoProyecto2;
    private javax.swing.JTextField jtfNumDptoProyecto3;
    private javax.swing.JTextField jtfNumProyecto;
    private javax.swing.JTextField jtfNumProyecto1;
    private javax.swing.JTextField jtfNumProyecto2;
    private javax.swing.JTextField jtfNumProyecto3;
    private javax.swing.JTextField jtfUbiProyecto;
    private javax.swing.JTextField jtfUbiProyecto2;
    private javax.swing.JTextField jtfUbiProyecto3;
    private javax.swing.JTabbedPane jtpContenidoABCC;
    // End of variables declaration//GEN-END:variables
}
