/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;

/**
 *
 * @author clara
 */
public class MenuTrabajaEn extends javax.swing.JPanel {
     Color c1 = new Color(162,65,107);
     Color c2 = new Color(190,65,100);
    /**
     * Creates new form MenuEmpleado
     */
    public MenuTrabajaEn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAltasTr = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnBajasTr = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnConsultasTr = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnCambiosTr = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(960, 100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAltasTr.setBackground(new java.awt.Color(162, 65, 107));
        btnAltasTr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAltasTr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAltasTrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAltasTrMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Altas");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btnAltasTrLayout = new javax.swing.GroupLayout(btnAltasTr);
        btnAltasTr.setLayout(btnAltasTrLayout);
        btnAltasTrLayout.setHorizontalGroup(
            btnAltasTrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAltasTrLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel3)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        btnAltasTrLayout.setVerticalGroup(
            btnAltasTrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAltasTrLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        add(btnAltasTr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 100));

        btnBajasTr.setBackground(new java.awt.Color(162, 65, 107));
        btnBajasTr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBajasTr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBajasTrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBajasTrMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bajas");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btnBajasTrLayout = new javax.swing.GroupLayout(btnBajasTr);
        btnBajasTr.setLayout(btnBajasTrLayout);
        btnBajasTrLayout.setHorizontalGroup(
            btnBajasTrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBajasTrLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel4)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        btnBajasTrLayout.setVerticalGroup(
            btnBajasTrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBajasTrLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        add(btnBajasTr, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 240, 100));

        btnConsultasTr.setBackground(new java.awt.Color(162, 65, 107));
        btnConsultasTr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultasTr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultasTrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultasTrMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Consultas");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btnConsultasTrLayout = new javax.swing.GroupLayout(btnConsultasTr);
        btnConsultasTr.setLayout(btnConsultasTrLayout);
        btnConsultasTrLayout.setHorizontalGroup(
            btnConsultasTrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConsultasTrLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(76, 76, 76))
        );
        btnConsultasTrLayout.setVerticalGroup(
            btnConsultasTrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConsultasTrLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(btnConsultasTr, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 240, 100));

        btnCambiosTr.setBackground(new java.awt.Color(162, 65, 107));
        btnCambiosTr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiosTr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCambiosTrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCambiosTrMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cambios");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btnCambiosTrLayout = new javax.swing.GroupLayout(btnCambiosTr);
        btnCambiosTr.setLayout(btnCambiosTrLayout);
        btnCambiosTrLayout.setHorizontalGroup(
            btnCambiosTrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCambiosTrLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(76, 76, 76))
        );
        btnCambiosTrLayout.setVerticalGroup(
            btnCambiosTrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCambiosTrLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(btnCambiosTr, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 240, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltasTrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltasTrMouseEntered
        btnAltasTr.setBackground(c2);
    }//GEN-LAST:event_btnAltasTrMouseEntered

    private void btnAltasTrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltasTrMouseExited
        btnAltasTr.setBackground(c1);
    }//GEN-LAST:event_btnAltasTrMouseExited

    private void btnBajasTrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBajasTrMouseEntered
        btnBajasTr.setBackground(c2);
    }//GEN-LAST:event_btnBajasTrMouseEntered

    private void btnBajasTrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBajasTrMouseExited
        btnBajasTr.setBackground(c1);
    }//GEN-LAST:event_btnBajasTrMouseExited

    private void btnCambiosTrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiosTrMouseEntered
        btnCambiosTr.setBackground(c2);
    }//GEN-LAST:event_btnCambiosTrMouseEntered

    private void btnCambiosTrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiosTrMouseExited
        btnCambiosTr.setBackground(c1);
    }//GEN-LAST:event_btnCambiosTrMouseExited

    private void btnConsultasTrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultasTrMouseEntered
        btnConsultasTr.setBackground(c2);
    }//GEN-LAST:event_btnConsultasTrMouseEntered

    private void btnConsultasTrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultasTrMouseExited
        btnConsultasTr.setBackground(c1);
    }//GEN-LAST:event_btnConsultasTrMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAltasTr;
    private javax.swing.JPanel btnBajasTr;
    private javax.swing.JPanel btnCambiosTr;
    private javax.swing.JPanel btnConsultasTr;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
